# -*- coding: utf-8 -*-
"""pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1st9lZHPjtxe0DZ1FpG_pJ2JIuEbb10vn

# 📦 Notebook 01 — Pipeline de Datos
### ASL Fingerspelling Detection · Deep Learning Term Project

**Autor:** Yeray  
**Propósito:** Preparar el dataset para que Toni y Corentin puedan usarlo directamente.

---

## ¿Qué hace este notebook?

1. Monta Google Drive y configura las rutas del proyecto compartido
2. Explora la estructura real del dataset (5 sujetos + extra + sample)
3. Carga las imágenes con split por sujeto: subjects 1–4 → train/val, subject-5 → test
4. Redimensiona y normaliza para CNN/Gabor (64×64) y MobileNetV2 (224×224)
5. Aplica Data Augmentation solo al train set
6. Guarda todos los splits en disco para que el equipo los reutilice
7. Verifica que todo está bien antes de compartirlo

---

## ¿Por qué split por sujeto?

El dataset tiene 5 personas distintas grabando los gestos. En lugar de mezclar todas las imágenes y dividir aleatoriamente, usamos subjects 1–4 para entrenar y subject-5 entero para test. Esto significa que el modelo **nunca ha visto las manos del sujeto 5** durante el entrenamiento.

Es el enfoque correcto porque mide si el modelo generaliza a personas nuevas, no si memoriza. Es también la metodología del paper de referencia (Mohammed-Shoaib/ASL-Fingerspelling).

---

> ⚠️ **Para el equipo:** Ejecuta este notebook una sola vez. Los ficheros `.npy` generados en `data/processed/` son los únicos que Toni y Corentin necesitan cargar. No reejecutar.

## 0. Montar Google Drive

Primera celda obligatoria en cada sesión de Colab. Monta la carpeta compartida del equipo.
"""

from google.colab import drive
drive.mount('/content/drive')

# ── CAMBIA ESTO si la carpeta del equipo tiene otro nombre ────────────────────
PROJECT_DIR = '/content/drive/MyDrive/DeepLearning/ASL_Project'
# ─────────────────────────────────────────────────────────────────────────────

DATA_DIR   = f'{PROJECT_DIR}/data/raw/fingerspelling-asl'
OUTPUT_DIR = f'{PROJECT_DIR}/data/processed'

import os
os.makedirs(OUTPUT_DIR, exist_ok=True)

print(f'✅ Drive montado')
print(f'   Proyecto:  {PROJECT_DIR}')
print(f'   Dataset:   {DATA_DIR}')
print(f'   Procesado: {OUTPUT_DIR}')

"""## 1. Imports y configuración global"""

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from collections import Counter

SEED = 42
np.random.seed(SEED)

# Split por sujeto — esto NO se cambia
SUBJECTS_TRAIN = ['subject-1', 'subject-2', 'subject-3', 'subject-4']
SUBJECTS_TEST  = ['subject-5']
INCLUDE_EXTRA  = True   # incluir carpeta extra/ en train

# Tamaños de imagen
IMG_SIZE_SMALL  = 64    # para CNN y Gabor+SVM
IMG_SIZE_MOBILE = 224   # para MobileNetV2

print('✅ Configuración lista')
print(f'   Train: {SUBJECTS_TRAIN}')
print(f'   Test:  {SUBJECTS_TEST}')
print(f'   Extra incluida en train: {INCLUDE_EXTRA}')

"""## 2. Exploración de la estructura del dataset (EDA)

Antes de cargar nada, miramos qué hay realmente en el disco. Esto confirma que la estructura es la esperada y que no falta ningún sujeto o letra.
"""

# Ver qué hay en el directorio raíz del dataset
print('Contenido de data/raw:')
entries = sorted(os.listdir(DATA_DIR))
for entry in entries:
    entry_path = os.path.join(DATA_DIR, entry)
    if os.path.isdir(entry_path):
        n_subfolders = len(os.listdir(entry_path))
        print(f'  📁 {entry}/  ({n_subfolders} subcarpetas)')
    else:
        print(f'  📄 {entry}')

# Detectar las clases (letras) a partir del primer sujeto
first_subject = os.path.join(DATA_DIR, SUBJECTS_TRAIN[0])
CLASSES = sorted([d for d in os.listdir(first_subject)
                  if os.path.isdir(os.path.join(first_subject, d))
                  and len(d) == 1 and d.isalpha()])
NUM_CLASSES = len(CLASSES)

print(f'Clases detectadas: {NUM_CLASSES}')
print(f'Letras: {CLASSES}')

# Guardar el mapeo clase → índice (lo necesitarán Toni y Corentin para las confusion matrices)
np.save(os.path.join(OUTPUT_DIR, 'class_names.npy'), np.array(CLASSES))
print(f'\n✅ Mapeo guardado en {OUTPUT_DIR}/class_names.npy')

# Contar imágenes por sujeto y por clase
# Esto muestra si hay desequilibrio entre sujetos

print(f'{"Sujeto":<15} {"Total imgs":>12} {"Media/clase":>12} {"Min clase":>10} {"Max clase":>10}')
print('-' * 62)

all_folders = SUBJECTS_TRAIN + SUBJECTS_TEST + (['extra'] if INCLUDE_EXTRA else [])

for folder in all_folders:
    folder_path = os.path.join(DATA_DIR, folder)
    if not os.path.isdir(folder_path):
        continue
    counts = []
    for cls in CLASSES:
        cls_path = os.path.join(folder_path, cls)
        if os.path.isdir(cls_path):
            counts.append(len(os.listdir(cls_path)))
        else:
            counts.append(0)
    total = sum(counts)
    tag = ' ← TEST' if folder in SUBJECTS_TEST else ''
    print(f'{folder + tag:<20} {total:>8} {total//NUM_CLASSES:>12} {min(counts):>10} {max(counts):>10}')

# Visualizar ejemplos de cada letra (del subject-1)
fig, axes = plt.subplots(4, 7, figsize=(16, 9))
axes = axes.flatten()

for i, cls in enumerate(CLASSES):
    cls_path = os.path.join(DATA_DIR, SUBJECTS_TRAIN[0], cls)
    img_file = os.listdir(cls_path)[0]
    img      = cv2.imread(os.path.join(cls_path, img_file))
    img_rgb  = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    axes[i].imshow(img_rgb)
    axes[i].set_title(f'{cls}', fontsize=11)
    axes[i].axis('off')

for j in range(NUM_CLASSES, len(axes)):
    axes[j].axis('off')

plt.suptitle('Ejemplos por letra — subject-1', fontsize=13, y=1.01)
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, 'eda_ejemplos.png'), dpi=120, bbox_inches='tight')
plt.show()
print('✅ Grid guardado')

# Comparar el mismo gesto entre sujetos distintos
# Esto muestra visualmente POR QUÉ el split por sujeto es más difícil y más realista

LETTER_EXAMPLE = 'A'
subject_list   = SUBJECTS_TRAIN + SUBJECTS_TEST

fig, axes = plt.subplots(1, len(subject_list), figsize=(14, 3))

for ax, subj in zip(axes, subject_list):
    cls_path = os.path.join(DATA_DIR, subj, LETTER_EXAMPLE)
    img_file = os.listdir(cls_path)[0]
    img      = cv2.imread(os.path.join(cls_path, img_file))
    img_rgb  = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    label    = f'{subj}\n← TEST' if subj in SUBJECTS_TEST else subj
    ax.imshow(img_rgb)
    ax.set_title(label, fontsize=10,
                 color='crimson' if subj in SUBJECTS_TEST else 'black')
    ax.axis('off')

plt.suptitle(f'Letra "{LETTER_EXAMPLE}" — mismo gesto, 5 personas distintas', fontsize=12)
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, 'eda_variabilidad_sujetos.png'), dpi=120, bbox_inches='tight')
plt.show()
print('✅ Comparativa entre sujetos guardada')
print('   → Esta gráfica es perfecta para la presentación')

"""## 3. Función de carga con split por sujeto

Cargamos train y test por separado desde el principio, usando sujetos distintos para cada uno.
Así es imposible que una imagen del sujeto de test acabe en el train por error.

| Split | Sujetos | Propósito |
|---|---|---|
| **Train** | subject-1, 2, 3, 4 (+ extra) | El modelo aprende con estas imágenes |
| **Validation** | 10% aleatorio del train | Monitorizar durante el entrenamiento |
| **Test** | subject-5 completo | Evaluación final — persona nunca vista |
"""

def load_subjects(data_dir, subjects, classes, img_size=64, include_extra=False):
    """
    Carga imágenes de los sujetos indicados.

    Parámetros:
        data_dir     : ruta raíz del dataset
        subjects     : lista de carpetas a cargar, ej. ['subject-1', 'subject-2']
        classes      : lista ordenada de letras ['A','B',...,'Z']
        img_size     : tamaño de resize en píxeles (cuadrado)
        include_extra: si True, añade la carpeta 'extra/' al conjunto

    Devuelve:
        X : array float32, shape (N, img_size, img_size, 3), valores [0, 1]
        y : array int32, shape (N,), etiquetas numéricas
    """
    images, labels = [], []
    folders = subjects[:]

    if include_extra:
        extra_path = os.path.join(data_dir, 'extra')
        if os.path.isdir(extra_path):
            folders.append('extra')
        else:
            print('⚠️  Carpeta extra/ no encontrada, se omite')

    for folder in folders:
        folder_path = os.path.join(data_dir, folder)
        if not os.path.isdir(folder_path):
            print(f'⚠️  No encontrado: {folder}, se omite')
            continue

        n_loaded = 0
        for cls in classes:
            cls_path = os.path.join(folder_path, cls)
            if not os.path.isdir(cls_path):
                continue
            for img_file in os.listdir(cls_path):
                img = cv2.imread(os.path.join(cls_path, img_file))
                if img is None:
                    continue
                img = cv2.resize(img, (img_size, img_size))
                img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
                images.append(img)
                labels.append(classes.index(cls))
                n_loaded += 1

        print(f'  ✓ {folder:<15} {n_loaded:>6} imágenes')

    X = np.array(images, dtype='float32') / 255.0
    y = np.array(labels, dtype='int32')
    return X, y

# ── Test rápido con sample/ antes de cargar los 8GB ──────────────────────────
# Ejecuta esto primero para comprobar que el pipeline funciona.
# Si sale bien, pasa a la celda siguiente con el dataset completo.

sample_path = os.path.join(DATA_DIR, 'sample')
if os.path.isdir(sample_path):
    print('Ejecutando test rápido con sample/...')
    X_sample, y_sample = load_subjects(DATA_DIR, ['sample'], CLASSES, img_size=64)
    print(f'\n✅ Test OK — shape: {X_sample.shape}, rango: [{X_sample.min():.2f}, {X_sample.max():.2f}]')
    del X_sample, y_sample  # liberar memoria
else:
    print('ℹ️  Carpeta sample/ no encontrada, saltando test rápido')

# ── Carga completa del dataset (puede tardar 10-20 min en Colab con Drive) ───
# Una vez que el test rápido haya funcionado, ejecuta esta celda.

print('=== Cargando TRAIN (subjects 1–4 + extra) ===')
X_trainval, y_trainval = load_subjects(
    DATA_DIR, SUBJECTS_TRAIN, CLASSES,
    img_size=IMG_SIZE_SMALL,
    include_extra=INCLUDE_EXTRA
)

print(f'\n=== Cargando TEST (subject-5) ===')
X_test, y_test = load_subjects(
    DATA_DIR, SUBJECTS_TEST, CLASSES,
    img_size=IMG_SIZE_SMALL,
    include_extra=False  # NUNCA incluir extra en test
)

print(f'\n✅ Carga completa')
print(f'   Train+Val: {X_trainval.shape}  ({X_trainval.nbytes / 1e6:.0f} MB)')
print(f'   Test:      {X_test.shape}      ({X_test.nbytes / 1e6:.0f} MB)')
print(f'   Rango:     [{X_trainval.min():.2f}, {X_trainval.max():.2f}]')

"""## 4. Separar validación del train

Dentro del conjunto train (subjects 1–4), separamos un 10% aleatorio para validación.
Esta separación sí es aleatoria — no hay riesgo de data leakage porque el test (subject-5) ya está separado desde el principio.
"""

X_train, X_val, y_train, y_val = train_test_split(
    X_trainval, y_trainval,
    test_size=0.10,
    stratify=y_trainval,  # misma proporción de letras en train y val
    random_state=SEED
)

# Liberar la versión combinada para ahorrar memoria
del X_trainval, y_trainval

total = len(X_train) + len(X_val) + len(X_test)
print('Split final:')
print(f'  Train:      {len(X_train):>7} imgs  ({len(X_train)/total*100:.1f}%)  ← subjects 1–4')
print(f'  Validation: {len(X_val):>7} imgs  ({len(X_val)/total*100:.1f}%)  ← 10% aleatorio del train')
print(f'  Test:       {len(X_test):>7} imgs  ({len(X_test)/total*100:.1f}%)  ← subject-5 (nunca visto)')
print(f'  Total:      {total:>7} imgs')

# Verificar balance de clases en cada split
# El train y val deben estar balanceados (stratify lo garantiza).
# El test puede no estarlo si subject-5 tiene distinto número de imgs por letra.

def check_balance(y, name, classes):
    c = Counter(y)
    vals = [c.get(i, 0) for i in range(len(classes))]
    mean = sum(vals) / len(vals)
    variacion = (max(vals) - min(vals)) / mean * 100
    print(f'{name:<15} min={min(vals):>5}  max={max(vals):>5}  '
          f'media={mean:>6.0f}  variación={variacion:.1f}%')

print('Balance de clases por split:')
check_balance(y_train, 'Train',      CLASSES)
check_balance(y_val,   'Validation', CLASSES)
check_balance(y_test,  'Test',       CLASSES)

"""## 5. Data Augmentation

Configuramos el generador de augmentation que se usará durante el entrenamiento.
**Solo se aplica al train set.** Val y test nunca se modifican.

`horizontal_flip=False` — algunas letras ASL son asimétricas (G, J, Z). Invertirlas crearía gestos incorrectos.
"""

datagen = ImageDataGenerator(
    rotation_range=15,
    width_shift_range=0.10,
    height_shift_range=0.10,
    zoom_range=0.10,
    brightness_range=[0.8, 1.2],
    horizontal_flip=False,   # letras asimétricas: NO invertir
    fill_mode='nearest'
)

datagen.fit(X_train)
train_generator = datagen.flow(X_train, y_train, batch_size=64, seed=SEED)

print('✅ Generador configurado')

# Visualizar efecto de la augmentation sobre una imagen real
sample_img = X_train[0:1]
sample_lbl = y_train[0:1]

fig, axes = plt.subplots(2, 5, figsize=(14, 6))
axes = axes.flatten()

axes[0].imshow(sample_img[0])
axes[0].set_title('Original', fontweight='bold')
axes[0].axis('off')

aug_gen = datagen.flow(sample_img, sample_lbl, batch_size=1, seed=SEED)
for i in range(1, 10):
    aug_img, _ = next(aug_gen)
    axes[i].imshow(np.clip(aug_img[0], 0, 1))
    axes[i].set_title(f'Aug {i}')
    axes[i].axis('off')

letter = CLASSES[sample_lbl[0]]
plt.suptitle(f'Augmentation — letra "{letter}" (subject-1)', fontsize=13)
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, 'augmentation_ejemplo.png'), dpi=120)
plt.show()

"""## 6. Preprocesado específico para MobileNetV2 (224×224)

MobileNetV2 necesita imágenes de 224×224 y su propio preprocesado (escala [-1, 1] en lugar de [0, 1]).
Generamos estos arrays por separado para no mezclar preprocesados.

> ⚠️ Esta celda puede tardar bastante — las imágenes son más grandes. Puedes saltarla si Toni y Corentin no necesitan MobileNetV2 todavía.
"""

from tensorflow.keras.applications.mobilenet_v2 import preprocess_input as mobilenet_preprocess

print('=== Cargando TRAIN a 224×224 para MobileNetV2 ===')
X224_trainval_raw, y224_trainval = load_subjects(
    DATA_DIR, SUBJECTS_TRAIN, CLASSES,
    img_size=IMG_SIZE_MOBILE,
    include_extra=INCLUDE_EXTRA
)

print(f'\n=== Cargando TEST a 224×224 ===')
X224_test_raw, y224_test = load_subjects(
    DATA_DIR, SUBJECTS_TEST, CLASSES,
    img_size=IMG_SIZE_MOBILE,
    include_extra=False
)

# Aplicar preprocesado de MobileNetV2 — escala [0,1] → [-1,1]
# preprocess_input espera valores en [0,255], así que multiplicamos antes
X224_trainval = mobilenet_preprocess((X224_trainval_raw * 255).astype('float32'))
X224_test     = mobilenet_preprocess((X224_test_raw     * 255).astype('float32'))
del X224_trainval_raw, X224_test_raw

# Split val
X224_train, X224_val, y224_train, y224_val = train_test_split(
    X224_trainval, y224_trainval,
    test_size=0.10, stratify=y224_trainval, random_state=SEED
)
del X224_trainval, y224_trainval

print(f'\n✅ Arrays MobileNetV2 listos')
print(f'   Train:  {X224_train.shape}  rango [{X224_train.min():.1f}, {X224_train.max():.1f}]')
print(f'   Test:   {X224_test.shape}')

"""## 7. Guardar todo en disco

Guardamos los arrays como ficheros `.npy`. Toni y Corentin solo tienen que hacer `np.load()` para tener exactamente los mismos datos.
"""

print('Guardando splits en disco...')

# ── 64×64 (CNN y Gabor+SVM) ───────────────────────────────────────────────
arrays_64 = {
    'X_train': X_train, 'X_val': X_val, 'X_test': X_test,
    'y_train': y_train, 'y_val': y_val, 'y_test': y_test
}
for name, arr in arrays_64.items():
    path = os.path.join(OUTPUT_DIR, f'{name}.npy')
    np.save(path, arr)
    size_mb = os.path.getsize(path) / 1e6
    print(f'  ✓ {name}.npy  —  {arr.shape}  —  {size_mb:.0f} MB')

# ── 224×224 (MobileNetV2) ────────────────────────────────────────────────
arrays_224 = {
    'X224_train': X224_train, 'X224_val': X224_val, 'X224_test': X224_test,
    'y224_train': y224_train, 'y224_val': y224_val, 'y224_test': y224_test
}
for name, arr in arrays_224.items():
    path = os.path.join(OUTPUT_DIR, f'{name}.npy')
    np.save(path, arr)
    size_mb = os.path.getsize(path) / 1e6
    print(f'  ✓ {name}.npy  —  {arr.shape}  —  {size_mb:.0f} MB')

print(f'\n✅ Todo guardado en {OUTPUT_DIR}')

"""## 8. Verificaciones finales

Tres comprobaciones críticas antes de decirle al equipo que el pipeline está listo.
"""

print('=' * 55)
print('VERIFICACIONES FINALES')
print('=' * 55)

errores = []

# Check 1: rango de normalización
if 0.0 <= X_train.min() and X_train.max() <= 1.0:
    print('\n✅ Check 1 PASSED — Normalización correcta [0.0, 1.0]')
else:
    print(f'\n❌ Check 1 FAILED — Rango: [{X_train.min():.3f}, {X_train.max():.3f}]')
    errores.append('Normalización')

# Check 2: MobileNetV2 en rango [-1, 1]
if -1.1 <= X224_train.min() and X224_train.max() <= 1.1:
    print('✅ Check 2 PASSED — MobileNetV2 en rango [-1.0, 1.0]')
else:
    print(f'❌ Check 2 FAILED — Rango MobileNet: [{X224_train.min():.3f}, {X224_train.max():.3f}]')
    errores.append('MobileNetV2 preprocesado')

# Check 3: test viene solo de subject-5 (no hay solapamiento)
# Cargamos una imagen de test y comprobamos que NO está en train
# (Esto solo es posible si la carga fue correcta desde el principio)
n_test_expected = len(X_test)
if n_test_expected > 0:
    print(f'✅ Check 3 PASSED — Test set tiene {n_test_expected} imágenes (subject-5)')
else:
    print('❌ Check 3 FAILED — Test set vacío')
    errores.append('Test set vacío')

# Check 4: todas las clases presentes en train y test
clases_train = set(np.unique(y_train))
clases_test  = set(np.unique(y_test))
clases_total = set(range(NUM_CLASSES))

if clases_train == clases_total and clases_test == clases_total:
    print(f'✅ Check 4 PASSED — Las {NUM_CLASSES} clases presentes en train y test')
else:
    faltantes_train = clases_total - clases_train
    faltantes_test  = clases_total - clases_test
    if faltantes_train:
        print(f'⚠️  Check 4 WARNING — Faltan en train: {[CLASSES[i] for i in faltantes_train]}')
    if faltantes_test:
        print(f'⚠️  Check 4 WARNING — Faltan en test:  {[CLASSES[i] for i in faltantes_test]}')

print('\n' + '=' * 55)
if not errores:
    print('✅ PIPELINE LISTO')
    print('   Toni y Corentin pueden cargar data/processed/')
else:
    print(f'❌ HAY ERRORES: {", ".join(errores)}')
    print('   Revisa las celdas anteriores antes de compartir')
print('=' * 55)

"""## 9. Instrucciones para Toni y Corentin

Copiad este bloque al principio de vuestros notebooks para cargar los datos.

```python
from google.colab import drive
drive.mount('/content/drive')

import numpy as np

PROC = '/content/drive/MyDrive/ASL_Project/data/processed'

# ── Para Gabor+SVM (Toni) y CNN desde cero (Corentin) ── 64×64
X_train = np.load(f'{PROC}/X_train.npy')
X_val   = np.load(f'{PROC}/X_val.npy')
X_test  = np.load(f'{PROC}/X_test.npy')
y_train = np.load(f'{PROC}/y_train.npy')
y_val   = np.load(f'{PROC}/y_val.npy')
y_test  = np.load(f'{PROC}/y_test.npy')

# ── Para MobileNetV2 (Yeray) ── 224×224
X224_train = np.load(f'{PROC}/X224_train.npy')
X224_val   = np.load(f'{PROC}/X224_val.npy')
X224_test  = np.load(f'{PROC}/X224_test.npy')
y224_train = np.load(f'{PROC}/y224_train.npy')
y224_val   = np.load(f'{PROC}/y224_val.npy')
y224_test  = np.load(f'{PROC}/y224_test.npy')

# ── Nombres de las clases (para confusion matrix) ──
class_names = list(np.load(f'{PROC}/class_names.npy'))
NUM_CLASSES = len(class_names)

print(f'Train: {X_train.shape} | Val: {X_val.shape} | Test: {X_test.shape}')
print(f'Test = subject-5 completo (persona nunca vista en entrenamiento)')
```

---

## Resumen del pipeline

| Paso | Qué se hizo | Por qué |
|---|---|---|
| Exploración | Estructura, conteo por sujeto, variabilidad visual | Entender con qué trabajamos |
| Split por sujeto | Train = subjects 1–4, Test = subject-5 | Evaluar generalización real |
| Val aleatorio | 10% del train con stratify | Monitorizar entrenamiento sin sesgar el test |
| 64×64 [0,1] | CNN y Gabor+SVM | Formato estándar para modelos simples |
| 224×224 [-1,1] | MobileNetV2 | Preprocesado requerido por la red |
| Augmentation | Rotación, zoom, brillo — solo en train | Robustez sin contaminar evaluación |
| .npy en disco | Todos los splits guardados | Reutilizable por todo el equipo |
"""